# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingtweets',
            name='tweets',
        ),
        migrations.AddField(
            model_name='trendingtweets',
            name='no_of_tweets',
            field=models.IntegerField(default=0),
        ),
    ]
